#!/bin/sh

##############################################################
# Bspwm settings
##############################################################
bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config borderless_monocle   false

bspc config window_gap            8
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

xsetroot -cursor_name left_ptr

##############################################################
# Auto-started programs
##############################################################
# Hotkey daemon
sxhkd &

# Bring kitty colour scheme into Xorg
xrdb merge ~/.config/X11/xresources &

# Set background
xwallpaper --focus ~/.config/X11/wallpaper.png &

# Compositor
picom &

# Status bar
killall -q polybar || polybar topBar &

# Web browser
pgrep "firefox" >/dev/null 2>&1 || firefox &

# Terminal emulator
pgrep "kitty" >/dev/null 2>&1 || kitty &
